### ISSUE TITLE
Hitting assertion in RewriteUtils.cpp:1471

### ISSUE THREAD

**Issue by octoploid** [csmith-project/creduce#141] opened 2017-07-02 10:00 UTC
I'm constantly hitting the assertion in RewriteUtils.cpp:1471.
(Sorry, I have no testcase at the moment)
```
===< pass_clang_binsrch :: replace-function-def-with-decl >===

clang_delta: RewriteUtils.cpp:1471: bool RewriteUtils::replaceFunctionDefWithStr(const clang::FunctionDecl*, const string&): Assertion `Body && "FunctionDecl is not a definition!"' failed.
sh: line 1: 106988 Aborted                 "/home/trippels/creduce/creduce/../clang_delta/clang_delta" --transformation=replace-function-def-with-decl --counter=1 --to-counter=9212 /home/trippels/tmp/creduce-vC5MYS/Metadata.ii > /home/trippels/tmp/Q9QuIz5vz
```

Perhaps it could be replaced by:
```diff
diff --git a/clang_delta/RewriteUtils.cpp b/clang_delta/RewriteUtils.cpp
index efc20cb9d92b..8cb53372e07f 100644
--- a/clang_delta/RewriteUtils.cpp
+++ b/clang_delta/RewriteUtils.cpp
@@ -1468,7 +1468,8 @@ bool RewriteUtils::replaceFunctionDefWithStr(const FunctionDecl *FD,
                                              const std::string &Str)
 {
   const Stmt *Body = FD->getBody();
-  TransAssert(Body && "FunctionDecl is not a definition!");
+  if (!Body)
+    return false;
   return !TheRewriter->ReplaceText(Body->getSourceRange(), Str);
 }
 ```

**Comment by chenyang78** [comment] 2017-07-06 03:12
@octoploid Thanks for reporting the issue! The patch could be a temporary workaround, but I think the root cause is likely somewhere else. If possible, could you attach a failing test? Thanks.

**Comment by octoploid** [comment] 2017-07-06 06:17
Take https://github.com/llvm-mirror/test-suite/blob/master/MultiSource/Benchmarks/tramp3d-v4/tramp3d-v4.cpp for example:

```
trippels@gcc67 ~ % clang++ --save-temps -Ofast -w tramp.cpp
trippels@gcc67 ~ % ~/creduce/clang_delta/clang_delta --transformation=replace-function-def-with-decl --counter=1 --to-counter=1000 --output=/dev/null tramp.ii
clang_delta: RewriteUtils.cpp:1471: bool RewriteUtils::replaceFunctionDefWithStr(const clang::FunctionDecl*, const string&): Assertion `Body && "FunctionDecl is not a definition!"' failed.
[1]    31170 abort      ~/creduce/clang_delta/clang_delta  --counter=1 --to-counter=1000  tramp.ii
```
I'm using LLVM trunk.

**Comment by chenyang78** [comment] 2017-07-07 04:07
Thanks, @octoploid 

I committed the fix into both master branch and llvm-svn-compatible branch.

**Closed by chenyang78** 2017-07-07 04:07 UTC
Labels: bug
