### ISSUE TITLE
CMake builds

### ISSUE THREAD

**Issue by vgvassilev** [csmith-project/creduce#86] opened 2016-02-29 15:52 UTC
It seems that cmake doesn't quite work:
  * It doesn't install creduce in ...bin/creduce
  * It seems there is no creduce script doesn't get created in the build dir.
  * There is one creduce.pl generated but the it's path to the creduce_modules is broken.

Which is the mid/long term build system? I personally prefer cmake, because adding new passes seems easier.

**Comment by eeide** [comment] 2016-02-29 16:00
"Patches welcome."

I tend to be the build-system maintainer for C-Reduce. I implemented the Automake-based system, and I don't currently have any plans to abandon it.

The Cmake-based system was contributed to C-Reduce. I don't really know Cmake, but I would like to learn about it, and when I do, I expect to update the Cmake-based build system. I don't plan to abandon it; rather, given LLVM's move to Cmake, I think that it is important to keep it.

In the meantime—until I have time to learn more about Cmake—I would be very happy to merge patches that bring C-Reduce's Cmake-based build system up to date!

**Comment by mpflanzer** [comment] 2016-02-29 17:00
I created the Cmake system to have a system which can be natively used on Windows.
Therefore it does not create all files required on Linux but some for Windows.
At that point I did not intend to use it for Linuzlx anyway.
If I have some spare time I might be able to update it and add Linux support. But feel free to work on it yourself. ;-)

**Comment by JVApen** [comment] 2016-03-05 19:06
Hi all,

I've just started building creduce on linux with CMake. I've noticed that at least 2 executables were not created. You can find a patch in attachment for the changes that do get this working. (Sorry, I'm a subversion person, so I still have to learn to work with git)

[cmake.diff.zip](https://github.com/csmith-project/creduce/files/159986/cmake.diff.zip)

**Comment by vgvassilev** [comment] 2016-03-05 19:36
@JVApen could you try my fork, there is a recent progress on cmake also on my fork, maybe you could try it out. It didn't build unifdef and so on...

**Comment by JVApen** [comment] 2016-03-05 19:48
Hi vgvassilev, tnx a lot, I've already integrated some of your changes the old way (copy paste). I'll wait until your pull request has been integrated. My current goal with it has been reached, namely checking if a bug in creduce is still there in the trunk version, so I'll be logging it soon.

PS: Be my guest in integrating my patch. (Note: It's also adding a build command for the topformflat executable)

**Comment by vgvassilev** [comment] 2016-03-05 19:49
@JVApen: thanks, it is in my fork!

**Comment by JVApen** [comment] 2016-04-21 20:58
Any progress on getting this integrated in trunk/master?

**Comment by vgvassilev** [comment] 2016-04-21 21:00
Well, not really. I need to do quite a lot of cherry picking and I am a little busy nowadays.

**Comment by eeide** [comment] 2016-04-22 01:43
Hi! The short answer to @JVApen's question is no:

> Any progress on getting this integrated in trunk/master?

I've postponed work on updating the CMake-based build until after I get the next release of C-Reduce done. (Just yesterday I updated the `INSTALL` file with a note to this effect.) After the release is done, I will get back to working on the CMake stuff.

Sorry.

**Comment by JVApen** [comment] 2016-04-22 11:17
No problem, I just was trying to get an idea about it.

**Comment by eeide** [comment] 2016-06-22 00:25
Today I pushed a large update to C-Reduce's CMake-based build system (commit 3064d2c).

The update make the CMake-based build system more complete, and it makes it work a lot more like the Automake-based build system.

Please give it a try to see if it works for you!

**Comment by chenyang78** [comment] 2016-06-23 04:22
I tried it with CMake 3.5.2 on my Ubuntu box. It works like a charm. Thanks, Eric!

**Comment by chenyang78** [comment] 2016-06-23 06:38
Hmm, actually one nit-pick: seems "git commit" can fail the incremental build. See if you can reproduce the behavior by following the steps below:

(0) assume that we successfully build creduce via "make" in a build dir;
(1) edit a clang_delta file, e.g. ReturnVoid.cpp;
(2) cd cmake/build/dir
(3) make
(4) cd -
(5) git commit ReturnVoid.cpp
(6) cd cmake/build/dir
(7) make

The "make" command at step (7) will re-build the entire source code of clang_delta. Perhaps the "git commit" command confused the timestamp that cmake relied on for incremental build?

**Comment by eeide** [comment] 2016-06-23 14:13
Yang Chen <notifications@github.com> writes:

> Hmm, actually one nit-pick: seems "git commit" can fail the incremental build.
> See if you can reproduce the behavior by following the steps below:

Thanks; I know about this issue.  See the commit message for 3064d2c.

> The "make" command at step (7) will re-build the entire source code of
> clang_delta. Perhaps the "git commit" command confused the timestamp that
> cmake relied on for incremental build?

The issue is that the CMake-based build system is smart enough to detect the
change to the compiler options, which triggers a recompilation of every C/C++
file.

The best way to resolve this is to change the way that we pass the git hash
into the binary.  Instead of communicating it through a command-line option, we
should commnicate it through a generated C/C++ file, which is regenerated every
time the git hash changes.

This is "simple enough," but it must also be implemented for the Automake-based
path as well.  That is slightly trickier.

I will fix this in the near future, since it is perhaps the main reason that
one wouldn't want to use the CMake-based build system.

Eric.

-- 
-------------------------------------------------------------------------------
Eric Eide <eeide@cs.utah.edu>  .         University of Utah School of Computing
http://www.cs.utah.edu/~eeide/ . +1 (801) 585-5512 voice, +1 (801) 581-5843 FAX

**Comment by chenyang78** [comment] 2016-06-23 20:10
I see. Thanks for the extra explanation.

- Yang

**Comment by eeide** [comment] 2016-06-25 18:38
Eric Eide <eeide@cs.utah.edu> writes:

> The best way to resolve this is to change the way that we pass the git hash
> into the binary.  Instead of communicating it through a command-line option,
> we should commnicate it through a generated C/C++ file, which is regenerated
> every time the git hash changes.
>
> This is "simple enough," but it must also be implemented for the
> Automake-based path as well.  That is slightly trickier.
>
> I will fix this in the near future, since it is perhaps the main reason that
> one wouldn't want to use the CMake-based build system.

FYI: I have implemented this, but not yet pushed it up.  After I test it a bit
more, I will push up my fix.

-- 
-------------------------------------------------------------------------------
Eric Eide <eeide@cs.utah.edu>  .         University of Utah School of Computing
http://www.cs.utah.edu/~eeide/ . +1 (801) 585-5512 voice, +1 (801) 581-5843 FAX

**Comment by eeide** [comment] 2016-06-25 20:20
Testing done. The recompile-almost-everything-on-commit behavior of the CMake-based build system should be fixed as of commit 9b0d493.

@chenyang78, please try it out and see if it works properly for you.

**Comment by chenyang78** [comment] 2016-06-26 06:54
On 2016-06-25 13:20, Eric Eide wrote:
> Testing done. The recompile-almost-everything-on-commit behavior of
> the CMake-based build system should be fixed as of commit 9b0d493 [1].
> 
> 
> @chenyang78 [2], please try it out and see if it works properly for
> you.
> 

It works. Thanks for the prompt fix!

- Yang

**Comment by eeide** [comment] 2016-07-01 19:43
The CMake-based build system seems to be working well, so I am going to close this issue.

I am also going to close pull request #87.

Thank you to everyone who contributed to the CMake-based build system!

**Closed by eeide** 2016-07-01 19:43 UTC
Labels: bug
