### ISSUE TITLE
segfault in multiple transformations

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [csmith-project/creduce#226] opened 2021-02-14 21:56 UTC
test.cc:

```c++
int main() {
    int x;
    struct s {
        int Ir;
        short __attribute__() & m ae0 __attribute__ 0;
    } f[] = {1e31 + -1 / -1ULL - sizeof(.1) &&
             __builtin_choose_expr(__builtin_constant_p(0), 0, &&l) & x};
```

PASS_BUG_INFO.TXT:

```txt
creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::remove-unused-function has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=remove-unused-function --counter=1 /tmp/creduce-WApmgm/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_000
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::callexpr-to-value has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=callexpr-to-value --counter=1 /tmp/creduce-Sknk2G/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_001
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::replace-callexpr has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=replace-callexpr --counter=1 /tmp/creduce-Tm32rU/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_002
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::simplify-callexpr has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=simplify-callexpr --counter=1 /tmp/creduce-ferEnt/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_003
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::remove-unused-enum-member has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=remove-unused-enum-member --counter=1 /tmp/creduce-eOgFKO/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_004
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::remove-enum-member-value has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=remove-enum-member-value --counter=1 /tmp/creduce-bC5ymu/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_005
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::remove-namespace has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=remove-namespace --counter=1 /tmp/creduce-sX6kcW/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_006
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::aggregate-to-scalar has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=aggregate-to-scalar --counter=1 /tmp/creduce-k99N5v/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_007
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::param-to-global has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=param-to-global --counter=1 /tmp/creduce-R5qDcl/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_008
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

creduce 2.10.0
fb91843
Linux
xxx
4.15.0-135-generic
#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
x86_64

***************************************************

pass_clang::param-to-local has encountered a bug:
crashed: "/usr/lib/x86_64-linux-gnu/clang_delta" --transformation=param-to-local --counter=1 /tmp/creduce-6vkQjn/test.cc

Please consider tarring up /data/zhan3299/docker_share/clang/creduce_bug_009
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

```

**Comment by marxin** [comment] 2021-03-09 15:32
Confirmed, crashes here:
```
==10129== Invalid read of size 1
==10129==    at 0x7E3CA2B: getStmtClass (Stmt.h:1149)
==10129==    by 0x7E3CA2B: clang::Stmt::getSourceRange() const (Stmt.cpp:264)
==10129==    by 0x86D6D02: (anonymous namespace)::InitListChecker::FillInEmptyInitForField(unsigned int, clang::FieldDecl*, clang::InitializedEntity const&, clang::InitListExpr*, bool&, bool) (SemaInit.cpp:693)
==10129==    by 0x86CA891: (anonymous namespace)::InitListChecker::FillInEmptyInitializations(clang::InitializedEntity const&, clang::InitListExpr*, bool&, clang::InitListExpr*, unsigned int, bool) (SemaInit.cpp:814)
==10129==    by 0x86CA1ED: (anonymous namespace)::InitListChecker::FillInEmptyInitializations(clang::InitializedEntity const&, clang::InitListExpr*, bool&, clang::InitListExpr*, unsigned int, bool) (SemaInit.cpp:0)
==10129==    by 0x86AF122: (anonymous namespace)::InitListChecker::InitListChecker(clang::Sema&, clang::InitializedEntity const&, clang::InitListExpr*, clang::QualType&, bool, bool, bool) [clone .llvm.7774296451234544464] (SemaInit.cpp:959)
==10129==    by 0x86C5C64: diagnoseListInit(clang::Sema&, clang::InitializedEntity const&, clang::InitListExpr*) (SemaInit.cpp:8739)
==10129==    by 0x86C039B: clang::InitializationSequence::Diagnose(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::ArrayRef<clang::Expr*>) (SemaInit.cpp:9190)
==10129==    by 0x86B8EB8: clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (SemaInit.cpp:7805)
==10129==    by 0x834DC4B: clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (SemaDecl.cpp:12053)
==10129==    by 0x7984DB4: clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (ParseDecl.cpp:2257)
==10129==    by 0x7982058: clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (ParseDecl.cpp:1986)
==10129==    by 0x797B3B4: clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (ParseDecl.cpp:1700)
==10129==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==10129== 
==10129== 
==10129== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==10129==  Access not within mapped region at address 0x0
==10129==    at 0x7E3CA2B: getStmtClass (Stmt.h:1149)
==10129==    by 0x7E3CA2B: clang::Stmt::getSourceRange() const (Stmt.cpp:264)
==10129==    by 0x86D6D02: (anonymous namespace)::InitListChecker::FillInEmptyInitForField(unsigned int, clang::FieldDecl*, clang::InitializedEntity const&, clang::InitListExpr*, bool&, bool) (SemaInit.cpp:693)
==10129==    by 0x86CA891: (anonymous namespace)::InitListChecker::FillInEmptyInitializations(clang::InitializedEntity const&, clang::InitListExpr*, bool&, clang::InitListExpr*, unsigned int, bool) (SemaInit.cpp:814)
==10129==    by 0x86CA1ED: (anonymous namespace)::InitListChecker::FillInEmptyInitializations(clang::InitializedEntity const&, clang::InitListExpr*, bool&, clang::InitListExpr*, unsigned int, bool) (SemaInit.cpp:0)
==10129==    by 0x86AF122: (anonymous namespace)::InitListChecker::InitListChecker(clang::Sema&, clang::InitializedEntity const&, clang::InitListExpr*, clang::QualType&, bool, bool, bool) [clone .llvm.7774296451234544464] (SemaInit.cpp:959)
==10129==    by 0x86C5C64: diagnoseListInit(clang::Sema&, clang::InitializedEntity const&, clang::InitListExpr*) (SemaInit.cpp:8739)
==10129==    by 0x86C039B: clang::InitializationSequence::Diagnose(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::ArrayRef<clang::Expr*>) (SemaInit.cpp:9190)
==10129==    by 0x86B8EB8: clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (SemaInit.cpp:7805)
==10129==    by 0x834DC4B: clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (SemaDecl.cpp:12053)
==10129==    by 0x7984DB4: clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (ParseDecl.cpp:2257)
==10129==    by 0x7982058: clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (ParseDecl.cpp:1986)
==10129==    by 0x797B3B4: clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (ParseDecl.cpp:1700)
==10129==  If you believe this happened as a result of a stack
==10129==  overflow in your program's main thread (unlikely but
==10129==  possible), you can try to increase the size of the
==10129==  main thread stack using the --main-stacksize= flag.
==10129==  The main thread stack size used in this run was 8388608.
```

**Comment by chenyang78** [comment] 2021-03-26 21:05
Looks like the issue came from Clang's ParseAST call-chain. For example, a vanilla ```clang``` also failed with the same failure:

```
$ clang --version
clang version 12.0.0 (https://github.com/llvm/llvm-project.git 75f50e15bf8fff6fba1d4678adedd33ef6a945e5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /backup/work/compilers/compiler-install/llvm-12.0.0-dev/bin
$ clang -c test.cc                                                                     
test.cc:5:25: error: expected '(' after '('                                                                                                                                                                 
    short __attribute__() & m ae0 __attribute__ 0;                                                                                                                                                          
                        ^                                                                                                                                                                                   
                        (                                                                                                                                                                                   
test.cc:5:30: error: expected ';' at end of declaration list                                                                                                                                                
    short __attribute__() & m ae0 __attribute__ 0;                                                                                                                                                          
                             ^                                                                                                                                                                              
                             ;                                                                                                                                                                              
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.                                                                       
Stack dump:                                                                                                                                                                                                 
0.      Program arguments: /backup/work/compilers/compiler-install/llvm-12.0.0-dev/bin/clang -c test.cc                                                                                                     
1.      test.cc:6:105: current parser token ';'                                                                                                                                                             
2.      test.cc:1:12: parsing function body 'main'                                                                                                                                                          
3.      test.cc:1:12: in compound statement ('{}')                                                                                                                                                          
 #0 0x0000000002f7987a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /backup/work/compilers/compiler-source/llvm-project/llvm/lib/Support/Unix/Signals.inc:563:11                                     
 #1 0x0000000002f79a4b PrintStackTraceSignalHandler(void*) /backup/work/compilers/compiler-source/llvm-project/llvm/lib/Support/Unix/Signals.inc:630:1                                                      
 #2 0x0000000002f7803b llvm::sys::RunSignalHandlers() /backup/work/compilers/compiler-source/llvm-project/llvm/lib/Support/Signals.cpp:70:5                                                                 
 #3 0x0000000002f7916e llvm::sys::CleanupOnSignal(unsigned long) /backup/work/compilers/compiler-source/llvm-project/llvm/lib/Support/Unix/Signals.inc:362:1                                                
 #4 0x0000000002eb3618 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) /backup/work/compilers/compiler-source/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:75:20 
 #5 0x0000000002eb38f3 CrashRecoverySignalHandler(int) /backup/work/compilers/compiler-source/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:389:1                                                  
 #6 0x00007fd612940890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)                                                                                                                         
...
``` 

I also checked clang binaries from LLVM 9.0 and 11.0. They both crashed in the same way. I am closing this one as not-a-creduce-issue.

**Closed by chenyang78** 2021-03-26 21:05 UTC
Labels: bug
